apiVersion: v1
kind: Service
metadata:
  name: skaffold
  labels:
    name: skaffold
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: skaffold
  type: LoadBalancer
